import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    image: {
        width: '100%',
        height: '100%',
    },
    overlay: {
        backgroundColor: 'rgba(13, 108, 69, 0.85)',
        padding: 16,
        width: '100%',
        height: '100%',
        flex: 1,
    },
    header: {
        marginBottom: 20,
    },
    title: {
        color: 'white',
        fontSize: 26,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderRadius: 12,
        paddingHorizontal: 12,
        marginTop: 10,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        height: 46,
        color: 'white',
        fontSize: 16,
    },
    formContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        padding: 16,
        borderRadius: 12,
        marginBottom: 20,
    },
    formTitle: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    entrada: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 10,
        height: 50,
        padding: 12,
        color: '#333',
        fontSize: 16,
        marginBottom: 12,
    },
    addButton: {
        backgroundColor: '#10B981',
        height: 50,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
    },
    addButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    listaContainer: {
        flex: 1,
    },
    tituloSeccion: {
        fontSize: 18,
        marginBottom: 15,
        color: 'white',
        fontWeight: 'bold',
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    },
    itemContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
    },
    deviceIconContainer: {
        backgroundColor: 'rgba(16, 185, 129, 0.2)',
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    infoContainer: {
        flex: 1,
    },
    nombreDispositivo: {
        color: 'white',
        fontSize: 17,
        fontWeight: 'bold',
    },
    modeloText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 14,
        marginTop: 2,
    },
    serieText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 13,
        marginTop: 2,
    },
    usuarioAsignado: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    usuarioText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 13,
        marginLeft: 4,
    },
    estadoBadge: {
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginTop: 6,
        alignSelf: 'flex-start',
    },
    estadoText: {
        fontSize: 12,
        fontWeight: 'bold',
    },
    actionButtons: {
        flexDirection: 'row',
    },
    editButton: {
        backgroundColor: 'rgba(8, 145, 178, 0.2)',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    deleteButton: {
        backgroundColor: 'rgba(225, 29, 72, 0.2)',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContainer: {
        padding: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        color: 'white',
        marginTop: 10,
        fontSize: 16,
    },
    emptyContainer: {
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyListText: {
        color: 'rgba(255, 255, 255, 0.7)',
        textAlign: 'center',
        fontSize: 16,
        fontWeight: 'bold',
        marginTop: 16,
    },
    emptySubText: {
        color: 'rgba(255, 255, 255, 0.5)',
        textAlign: 'center',
        fontSize: 14,
        marginTop: 8,
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalView: {
        backgroundColor: 'white',
        borderRadius: 16,
        width: '90%',
        padding: 0,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        overflow: 'hidden',
    },
    modalHeader: {
        backgroundColor: '#10B981',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
    },
    closeButton: {
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalForm: {
        padding: 16,
    },
    inputLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 5,
        marginLeft: 2,
    },
    modalInput: {
        width: '100%',
        height: 50,
        backgroundColor: '#f5f5f5',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#ddd',
        padding: 12,
        marginBottom: 16,
        fontSize: 16,
    },
    modalButtons: {
        flexDirection: 'row',
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    modalButton: {
        flex: 1,
        height: 55,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonCancel: {
        backgroundColor: '#f5f5f5',
        borderRightWidth: 0.5,
        borderRightColor: '#ddd',
    },
    buttonSave: {
        backgroundColor: '#10B981',
        borderLeftWidth: 0.5,
        borderLeftColor: '#ddd',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#666',
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
    },
});